import { PERMISSIONS } from './permissions.constants';

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  superadmin: Object.values(PERMISSIONS),

  baker: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.SHOP_READ,
    PERMISSIONS.SHOP_UPDATE,
  ],

  customer: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.SHOP_READ,
  ],
};
